
@hostname = ec2-3-34-197-155.ap-northeast-2.compute.amazonaws.com
@hostname = localhost
# @port = 4000 
@port = 8090

@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET http://{{host}}/api/public/test1
Content-Type: {{contentType}}

###
GET http://{{host}}/api/public/management/reports
Content-Type: {{contentType}}


###
POST http://{{host}}/auth/signin
Content-Type: {{contentType}}

{
  "usernameOrEmail": "pilseong",
  "password": "passwor"
}

###
POST http://{{host}}/auth/signin
Content-Type: {{contentType}}

{
  "usernameOrEmail": "noel@gmail.com",
  "password": "noel"
}

### signup user
POST http://{{host}}/auth/signup HTTP/1.1
Content-Type: {{contentType}}

{
  "username": "noel",
  "name": "noelheo",
  "email": "noel@gmail.com",
  "password": "noel"
}